
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aoun5
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        space = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        link = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        sign_up = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        space.setBackground(new java.awt.Color(255, 255, 255));
        space.setForeground(new java.awt.Color(255, 0, 0));
        space.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_customer_50px_1.png"))); // NOI18N
        space.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 262, 52, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iPad, Nexus 9 – 1.png"))); // NOI18N
        space.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, 250));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email");
        space.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 395, 81, 53));

        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        space.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 407, 214, 23));
        space.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 436, 214, 12));

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        space.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 466, 98, 45));
        space.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 500, 220, 12));

        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        space.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 480, 195, -1));

        link.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        link.setForeground(new java.awt.Color(255, 0, 0));
        link.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        link.setText("   Forget Password?");
        space.add(link, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 201, 30));

        login.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOGIN");
        space.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 333, 91, 19));

        warning.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        space.add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 518, 177, 26));

        submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submit.setIcon(new javax.swing.ImageIcon("C:\\Users\\aoun5\\Downloads\\button (5).png")); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        space.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 580, 130, 50));

        sign_up.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sign_up.setIcon(new javax.swing.ImageIcon("C:\\Users\\aoun5\\Downloads\\button (2).png")); // NOI18N
        sign_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_upMouseClicked(evt);
            }
        });
        space.add(sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 116, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(space, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
         warning.setText("");
     String user=email.getText();

     String pass=password.getText();
    if(user.trim().isEmpty()&& pass.trim().isEmpty())
     {
     warning.setText("Enter email & password");
     }
     else if(user.trim().isEmpty())
     {
     warning.setText("enter email");
     }
     else if(pass.trim().isEmpty())
     {
     warning.setText("enter  password");
     }
     if(user.equals("admin")&&pass.equals("123")){
//          String url="jdbc:sqlserver:sqlsrv\\sqlexpress;databaseName=record";
//          String username= "sa";
//          String passwordd="Zaib7810";
//         try {
//             Connection connection = DriverManager.getConnection(url, user, passwordd);
//             String sql = "INSERT INTO login (name,mark)"
//                     +"VALUES ('user','pass')";
//                     } catch (SQLException e) {
//                         System.out.println("oops error");
//         }
//         sign_up obj=new sign_up();
//         obj.setVisible(true);
     
        JOptionPane.showMessageDialog(null, "login succesfully","login",JOptionPane.INFORMATION_MESSAGE); }
     else {
         
     if(user!="admin" && pass!="123"){
      JOptionPane.showMessageDialog(null, "Wrong email or password","login",JOptionPane.INFORMATION_MESSAGE);
     }
     else{
         JOptionPane.showMessageDialog(null, "login failed","login",JOptionPane.INFORMATION_MESSAGE);
     }
     
    }//GEN-LAST:event_submitMouseClicked
    }
    private void sign_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_upMouseClicked
        // TODO add your handling code here:
          sign_up sign= new sign_up();
        sign.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sign_upMouseClicked
//      else{
//      JOptionPane.showMessageDialog(null, "login failed","login",JOptionPane.INFORMATION_MESSAGE);
//      }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel link;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel sign_up;
    private javax.swing.JPanel space;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
